"""Initial migration

Revision ID: 35f45b84352b
Revises: 
Create Date: 2025-03-08 18:55:18.869883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f45b84352b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('s_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('s_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Email', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('chapters',
    sa.Column('c_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('desc', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['s_id'], ['subjects.s_id'], ),
    sa.PrimaryKeyConstraint('c_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student_details',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('qualification', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('profile_picture_name', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.LargeBinary(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_table('mock',
    sa.Column('m_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('no_of_ques', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['c_id'], ['chapters.c_id'], ),
    sa.PrimaryKeyConstraint('m_id')
    )
    op.create_table('question',
    sa.Column('q_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_id', sa.Integer(), nullable=True),
    sa.Column('statement_text', sa.String(length=50), nullable=True),
    sa.Column('statement_pic_name', sa.String(length=50), nullable=True),
    sa.Column('statement_pic', sa.LargeBinary(), nullable=True),
    sa.Column('statement_type', sa.String(length=10), nullable=True),
    sa.Column('o_id', sa.Integer(), nullable=True),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('neg_marking', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['m_id'], ['mock.m_id'], ),
    sa.PrimaryKeyConstraint('q_id')
    )
    op.create_table('scores',
    sa.Column('sc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('m_id', sa.Integer(), nullable=True),
    sa.Column('u_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('positive_score', sa.Integer(), nullable=True),
    sa.Column('time_req', sa.Integer(), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['m_id'], ['mock.m_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['student_details.u_id'], ),
    sa.PrimaryKeyConstraint('sc_id')
    )
    op.create_table('options',
    sa.Column('q_id', sa.Integer(), nullable=True),
    sa.Column('o_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement_text', sa.String(length=50), nullable=True),
    sa.Column('statement_pic_name', sa.String(length=50), nullable=True),
    sa.Column('statement_pic', sa.LargeBinary(), nullable=True),
    sa.Column('statement_type', sa.String(length=10), nullable=True),
    sa.Column('correctness', sa.Boolean(create_constraint=10), nullable=True),
    sa.ForeignKeyConstraint(['q_id'], ['question.q_id'], ),
    sa.PrimaryKeyConstraint('o_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('options')
    op.drop_table('scores')
    op.drop_table('question')
    op.drop_table('mock')
    op.drop_table('student_details')
    op.drop_table('chapters')
    op.drop_table('user')
    op.drop_table('subjects')
    # ### end Alembic commands ###
